import React from 'react';
export const metadata = {
    title: 'Profile | Next Js',
    description: 'Generated by create next app',
  }
const ProfilePage = () => {
    return (
        <div>
            Profile
        </div>
    );
};

export default ProfilePage;