import React from 'react';
export const metadata = {
    title: 'Dashboard | Next Js',
    description: 'Generated by create next app',
  }
const layout = ({children}) => {
    return (
        <div>
            <nav>
                sideber
            </nav>
            {children}
        </div>
    );
};

export default layout;