import React from 'react';
export const metadata = {
    title: 'Home | Dashboard | Next Js',
    description: 'Generated by create next app',
  }
const DashboardPage = () => {
    return (
        <div>
            Dashboard Home
        </div>
    );
};

export default DashboardPage;